### ISSUE TITLE
Selecting another graph on the graph list does not update some options

### ISSUE THREAD

**Issue by WagnerGFX** [stuerp/foo_vis_spectrum_analyzer#34]
### Where?
- Configure Window > Graphs

### How it's working now:
- When switching to another graph item on the list, only checkboxes update. Dropdowns and number boxes keep the same values visually.
- Known values not being visually updated:
  - X Axis Mode Dropdown
  - X Axis Mode Dropdown
  - Amplitude Range
  - Amplitude Step
  - Style > Gradient % field

![boxes1](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/59dbd239-cd17-44bd-80c1-f17f306818f4)
![boxes2](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/c4126db3-e8ae-433a-a571-284999298c1c)

### Expected Behavior:
- All the values should reflect the current selected graph when changing items on the list.

### System Info:
- Windows 10 22H2
- Foobar2000 v1.6.16
- Visualizer v0.7.2.0
- CPU i7-2600k
- GPU GTX 1650

### Notes:
- I'm aware the requirements say Foobar2000 v2.0, but I cannot use it yet due to some components still not supporting it (mostly Spider Monkey Panel).
- If the bug is exclusive to versions lower than v2.0, then the issue can be closed.

**Comment by stuerp** [comment]
Thank you for the detailed report. Confirmed. I don't know how I missed that. Fixed in the next version.

**Comment by WagnerGFX** [comment]
When testing the alpha1 version, I can confirm the Graph settings are holding when changing between each graph item, at least for the drop boxes, check boxes and number fields.
The ones still not behaving well are the arrow buttons for the number fields, they don't update when I change the values manually or switch between graphs.

One example is changing the amplitude range from -70 to -90 manually. When I press the arrow down after that, it will change to -71 instead of -91.
The same still applies when changing between graphs.

The gradient color % seem to always apply spread whenever I change, add or remove a color.

**Comment by stuerp** [comment]
Good catch. The up/down controls are fixed in the next version.

The gradient color % was addressed in 0.7.4.1.

**Comment by stuerp** [comment]
@WagnerGFX ,

Included in: https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.5.0-alpha1

**Comment by WagnerGFX** [comment]
> Good catch. The up/down controls are fixed in the next version.

Switching graphs update the values correctly, the arrows also follow that value.
On the other hand, I still get an issue where I change a value manually and the arrows still consider the previous value when clicked.

> The gradient color % was addressed in 0.7.4.1.

The gradient % now stay in place when adding or removing colors, but I'm not being able to edit them by double-clicking anymore.
Also, the % doesn't update when changing between visual elements. I have to click again on the selected color to update the box.

I've also noticed that, when Amplitude-Based is enabled, changing color sources for Bar Area has no effect and it keeps applying the gradient color.
If needed, I can open a separate issue, as it seems to be a side effect of the new amplitude feature.

**Comment by stuerp** [comment]
> I've also noticed that, when Amplitude-Based is enabled, changing color sources for Bar Area has no effect and it keeps applying the gradient color. If needed, I can open a separate issue, as it seems to be a side effect of the new amplitude feature.

That's to be expected, isn't it? The amplitude determines the color. How did you expect it to behave?

**Comment by WagnerGFX** [comment]
> That's to be expected, isn't it? The amplitude determines the color. How did you expect it to behave?

Ops, I didn't explain it correctly 😅

Right now, when the Amplitude checkbox is enabled, changing to another color source will still keep gradient applied. I have to move back to gradient, disable Amplitude and then change the color source again.

Since amplitude is an option for gradients, switching to another color source should ignore that option, specially since the checkbox gets disabled when switching.

**Comment by stuerp** [comment]
I get it. I blocked that scenario in the rendering code but forgot to add the rules to the configuration dialog.

**Comment by stuerp** [comment]
> The gradient % now stay in place when adding or removing colors, but I'm not being able to edit them by double-clicking anymore. Also, the % doesn't update when changing between visual elements. I have to click again on the selected color to update the box.

A regression because I added double-click to the Presets and an oversight. Both fixed in the next version.

**Comment by stuerp** [comment]
https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.5.0-alpha2
